spring:
  application:
    name: UZCARD-SERVICE
  datasource:
    username: postgres
    password: root123
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 7779

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka